onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/g_CLK_DIV
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/g_spi_max_lgt
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/rst_n
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/sys_clk
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/sys_start_p
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/sys_tx_lgt
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/sys_rx_lgt
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/sys_done_p
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/sys_busy
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/sys_txd_rd_p
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/sys_txd
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/sys_rxd_dv_p
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/sys_rxd
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/spi_cs
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/spi_clk
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/spi_mosi
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/spi_miso
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_start_p_d
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_sys_busy_d
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_mem_sys_tx_lgt
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_mem_sys_rx_lgt
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_spiHz
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_spiHz_rst
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_spiHz_en
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_spiHz_p
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_halfe_spiHz_p
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_8bit
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_8bit_rst
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_8bit_en
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_8bit_p
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_tx_en
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_tx_lgt
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_tx_rd_p
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_tx_rd_p_d
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_rx_en
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_cpt_rx_lgt
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_txd_sr
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_txd_fs
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_rxd_sr
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_spi_clk
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_spi_cs
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_sys_done_p
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/s_sys_busy
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_CLK_DIV_CPT_LGT
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_CLK_FULL_PERIODE
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_CLK_HALF_PERIODE
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_PERIODE
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_HALF_PERIODE
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_8BIT_CPT_LGT
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_8BIT_SENT
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_CPT8B_SHIFT_TX
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_READ_NEXT_DATA
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_CPTCLK_SHIFT_TX
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_CPTCLK_LAST_TX_SHIFT
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_CPTCLK_SHIFT_RX
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_RD_P_DELAY
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_START_P_D_LGT
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_START_SPI_OK
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_START_CS_OK
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_STOP_CS
add wave -noupdate /tb_spi_master_gen/u_spi_master_gen/c_STOP_DONE
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {17940 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {51614 ns}
